/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `student`;

CREATE TABLE `student` (
  `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `age` INT NOT NULL)
 ENGINE=InnoDB;

